### ISSUE TITLE
Class Carro

### ISSUE THREAD

**Issue by PedroSenaCabral** [PedroSenaCabral/Estacionamento#2]
Criar classe carro

**Comment by Mateus-Brito** [comment]
criei os arquivos iniciais, https://github.com/PedroSenaCabral/Estacionamento/tree/ClasseCarro.

**Comment by Mateus-Brito** [comment]
falta adicionar o método put, segundo franklin ele já está terminando.

**Comment by franklinluiz2000** [comment]
Pessoal método "put" adicionado a classe Carro.
