### ISSUE TITLE
Criar arquivo do estacionamento

### ISSUE THREAD

**Issue by jerffesongd** [PedroSenaCabral/Estacionamento#23]
Criar uma classes para gerenciar o acesso um arquivo(binário ou texto) para que seja possível salvar as informações da ocorrência.

- [x]  Ao iniciar o programa, deve-se verificar se o arquivo existe, senão, deve-se criar o arquivo. (método main)

- [x] Criar um método nessa classe, que receba um ocorrência como parâmetro  e salve no arquivo.

**Comment by gdiael** [comment]
As alterações estão sendo feitas na branch "arquivos"

Vão ser dois arquivos, um para os veículos e outro para as ocorrências.

- [ ] Gravação do arquivo de veículos
- [ ] Gravação do arquivo de ocorrências
- [ ] Leitura do arquivo de veículos
- [ ] Leitura do arquivo de gravação
