### ISSUE TITLE
Calcular valor do estacionamento

### ISSUE THREAD

**Issue by jerffesongd** [PedroSenaCabral/Estacionamento#29]
Criar um método que receba a placa de um veiculo e retorne o valor do estacionamento.

**Comment by gdiael** [comment]
Valor do estacionamento está calculado dentro da classe Ocorrencia
Algumas ponderações sobre o formato da tabela:
- Acho que o valor da diário deveria ser membro da tabela
- Acho que o valor do preço por hora deveria ser membro da tabela
